<?php 

if($this->produto!=NULL){
    $acao = 'Adicionar';    
    $id = $this->produto->getIdProduto();
    $descricao = $this->produto->getDescricao();
    $descricaoCompleta = $this->produto->getDescricaoCompleta();
    $_unidade = $this->produto->getUnidade();
    $_tipo = $this->produto->getTipo();
}  else{
        $acao = 'Editar';
}

?>

<script language="javascript">
    function contarCaracteres() {
        var campo = document.getElementById('contarTxt');
        var texto = document.getElementById('descricaoCompletaTxt').value;
        var digitados = texto.length;
        var restante = 20000 - digitados;
        campo.innerHTML = restante;
    }   
</script>

<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title"><?=$acao?> produto</h3>
            </div>
            <?php if($this->produto == NULL):?>
                <form class="form-horizontal" id="produto-form" role="form" method="POST" action="<?php echo $this->url('produtos', array('action' => 'adicionar')); ?>">
            <?php else:?>
                <form class="form-horizontal" id="produto-form" role="form" method="POST" action="<?php echo $this->url('produtos', array('action' => 'editar', 'id' => $id)); ?>">
            <?php endif;?>
                    
            <div class="panel-body">
                <div class="form-group">
                    <label for="tipoSlct" class="col-lg-3 col-md-3 control-label">Tipo:</label>
                    <div class="col-lg-9 col-md-9">
                        <select name="tipoSlct" class="form-control" id="tipoSlct">
                            <option>----Selecione um tipo de produto----</option>
                            
                            <?  foreach ($this->tiposProduto as $tipoProduto):?>
                                <?if($tipoProduto->getDescricao() == $_tipo):?>
                                    <option value="<?=$tipoProduto->getIdTipoProduto()?>" selected="selected"><?=$tipoProduto->getDescricao()?></option>
                                <?else:?>
                                    <option value="<?=$tipoProduto->getIdTipoProduto()?>"><?=$tipoProduto->getDescricao()?></option>
                                <?endif;?>
                            <?  endforeach;?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="unidadeSlct" class="col-lg-3 col-md-3 control-label">Unidade:</label>
                    <div class="col-lg-9 col-md-9">
                        <select name="unidadeSlct" class="form-control" id="unidadeSlct">
                            <option>----Selecione uma unidade----</option>
                            
                            <?  foreach ($this->unidades as $unidade):?>
                                <?if($id != $unidade->getIdUnidade()):?>
                                    <?if($unidade->getDescricao() == $_unidade):?>
                                        <option value="<?=$unidade->getIdUnidade()?>" selected="selected"><?=$unidade->getDescricao()?></option>
                                    <?else:?>
                                        <option value="<?=$unidade->getIdUnidade()?>"><?=$unidade->getDescricao()?></option>
                                    <?endif;?>
                                <?endif;?>
                            <?  endforeach;?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="descricaoTxt" class="col-lg-3 col-md-3 control-label">Descrição:</label>
                    <div class="col-lg-9 col-md-9">
                        <input type="text" name="descricaoTxt" class="form-control" 
                               id="descricaoTxt" placeholder="Tipo de produto de exemplo"
                               value="<?=$descricao?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="descricaoCompletaTxt" class="col-lg-3 col-md-3 control-label">Descrição Completa:</label>
                    <div class="col-lg-9 col-md-9">
                        <textarea rows="10" cols="50" name="descricaoCompletaTxt" class="form-control" 
                               id="descricaoCompletaTxt" value="<?=$descricaoCompleta?>" onkeydown="contarCaracteres()"
                               onkeyup="contarCaracteres()" onfocus="contarCaracteres()"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label for="contarTxt" class="col-lg-3 col-md-3 control-label">Caracteres restantes:</label>
                    <div class="col-sm-2">
                        <label name="contarTxt" class="form-control"
                               id="contarTxt" width="1" value="<?=$contarTxt?>">
                        </label>
                    </div>
                </div>
            </div>
            <div class="panel panel-footer center">
                <a href="<?=$this->url('produtos', array('action' => 'index'))?>" class="btn btn-default" title="Voltar"><span class="glyphicon glyphicon-backward"></span> Voltar</a>
                <button type="submit" class="btn btn-default">Enviar</button>
            </div>
        </div>
    </div>
</div>

<div id="dialog" title="Erro">

</div>

<? $this->headScript()->captureStart(); ?>

$(document).ready(function(){
    $('input[type=text]').blur(function() {
        $(this).val($(this).val().toUpperCase());
    });
 
    $( "#dialog" ).dialog({
        autoOpen: false,
        modal: true,
        close: function( event, ui ) {
            $( this ).empty();
        },
        buttons: {
            Ok: function() {
                $( this ).empty();
                $( this ).dialog( "close" );
            }
        },
        show: {
            effect: "blind",
            duration: 100
        },
        hide: {
            effect: "blind",
            duration: 100
        }
    });

    $('#produto-form').validate({
        debug: false,
        onkeyup: false,
        errorClass: "invalid-input",
        errorPlacement: function(error,element) {
            error.appendTo("#dialog");
            $( "#dialog" ).dialog('open');
            return true;
        },
        
    });
    
    $('#descricaoTxt')
            .rules("add", {
                required: true,
                minlength: 5,
                maxlength: 255,
                messages: {
                    required: "A descricao do produto é obrigatório.<br>",
                    minlength: "A descricao do produto deve ter no mínimo 5 caracteres.<br>",
                    maxlength: "A descricao do produto deve ter no máximo 255 caracteres.<br>",
                }
    });
});

<? $this->headScript()->captureEnd(); ?>